server:
  port: 9000  

spring:
  profiles:
    active: dev
  application:
    name: springboot-keycloak-embedded

keycloak:
  custom:
    server.contextPath: /auth
  mqttPublisher:
    provider: "logger"

  emailSender:
    provider: "mqtt"





